# Generated by Django 3.2.1 on 2021-05-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem_type',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('problem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer', models.IntegerField()),
                ('blank_num', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', models.CharField(max_length=2000)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.user')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.problem_type')),
            ],
        ),
    ]
