# Generated by Django 3.2.1 on 2021-05-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
